### ISSUE TITLE
TODO: Excercises

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rosstat-kep-data#117]
- [x] R/[pandas data interface](https://github.com/epogrebnyak/rosstat-kep-data/blob/master/interface_pandas.py) + [retrieval examples](https://github.com/epogrebnyak/rosstat-kep-data/blob/three_src_version/prekep/kep_example.py) + edit readme.md
- [ ] [research questions](https://github.com/epogrebnyak/rosstat-kep-data/blob/master/notes/questions.md) and [research guidelines](https://github.com/epogrebnyak/rosstat-kep-data/issues/101)
- [ ] seasonality task

Addressed also #100, #101, #92

**Comment by epogrebnyak** [comment]
Remaining:
- [x] [R interface](https://github.com/epogrebnyak/rosstat-kep-data/blob/master/interface.r)  
- [ ] [more exercises](https://github.com/epogrebnyak/rosstat-kep-data/blob/master/notes/time_series_tasks.md)
- [ ] test pandas interface

**Comment by epogrebnyak** [comment]
https://github.com/epogrebnyak/rosstat-kep-data/blob/master/notes/time_series_tasks.md
