### ISSUE TITLE
Comment todo list 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rosstat-kep-data#135]
Done
====
-  [x] исправить ошибку дублирвания данных в reader.py (скорее всего устарел "__spec.txt") 
<https://github.com/epogrebnyak/data-rosstat-kep/issues/136>

Что надо сделать
===========

**Задача 1. Расширить прочтение данные в reader.py**
-  [ ] продвигаться дальше по строкам и добавлять новые контрольные значения для годовых переменных в reader.py 

**Задача 2. Текущий рефакторинг кода без добавления новых функций**
-  [ ] разные FIX и TODO в текущих файлах (без добавления новых функций)

Split функции 
-  [ ] doctest для <https://github.com/epogrebnyak/data-rosstat-kep/issues/139>
-  [ ] доработка структуры файлов, например: вынести split* функции в отдельный модуль 
-  [ ] есть ситуации, когда для функции нужен год?
 
**Задача 3. Тестирование**
reader,py
 - [ ] п. 1 - reader.py - assert переделать в тесты
-  [ ] написать код проверки "не должно быть двух значений для одной точки"

тесты, унаследованные от parsing_demo.py 
  - [ ] восстановить имеющиеся закомментаированные тесты в datapoints.py
<https://github.com/epogrebnyak/data-rosstat-kep/issues/137>
+ использовать Tempfile для тестов 

более ранние тесты
  - [ ] тесты из прошлой "длинной" версии подтянуть, там были разные fixtures

 
**Задача 4. Генерировать документацию** 
 -  [ ] сделать скрипт под windows, который генерирует документацию для kep2 с помощью pydoc (отдельно стоящие файлы  удается генерировать, а для всего пакета - нет). <https://github.com/epogrebnyak/data-rosstat-kep/issues/138>

 
Что (пока) не делаем
==============

 **Новая версия с сегментами:**
-  [ ] нужен разбор CSV на сегменты, соотвествующие дополнительным определениям парсинга
-  [ ] правильный выбор дополнительной фукнции разбора 
-  [ ] писать для этого тесты

**Еще функции:**
-  [ ] получить название переменной по обозначению
-  [ ] получить размерность переменной по обозначению
